# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.1
language: objective-c
podfile: Example/Podfile

env:
  global:
    - LANG=en_US.UTF-8
    - COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=true

cache:
  - bundler
  - cocoapods

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sleep 5

# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/LeeGo.xcworkspace -scheme LeeGo-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
